version: "3"

services:
  event-store:
    image: "mongo"
    environment:
      - MONGODB_INITDB_DATABASE=aster
      - MONGODB_INITDB_ROOT_USERNAME=aster
      - MONGODB_INITDB_ROOT_PASSWORD=rootpa55
    ports:
      - "27014:27017"
  state-store:
    image: "redis"
    ports:
      - "6376:6379"
  product-state-store:
    image: "redis"
    ports:
      - "6381:6379"
