version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=inventoryservice
      - RABBITMQ_DEFAULT_PASS=pa55
    ports:
      - "5672:5672"
      - "15672:15672"
