version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3.10-management"
    environment:
      - RABBITMQ_DEFAULT_USER=aster
      - RABBITMQ_DEFAULT_PASS=pa55
    ports:
      - "15672:15672"
      - "5672:5672"
