package money

import "errors"

type Currency struct {
	Code          string
	DecimalDigits int
	Symbol        string
}

var ErrCurrencyNotFound = errors.New("currency not found")

func NewCurrency(code string) (*Currency, error) {
	currency, ok := currencies[code]
	if !ok {
		return nil, ErrCurrencyNotFound
	}

	return currency, nil
}

func (c *Currency) IsEqualTo(to *Currency) bool {
	return c.Code == to.Code
}

var currencies = map[string]*Currency{
	"AED": {Symbol: "\u062f.\u0625", DecimalDigits: 2, Code: "AED"},
	"AFN": {Symbol: "Af", DecimalDigits: 2, Code: "AFN"},
	"ALL": {Symbol: "L", DecimalDigits: 2, Code: "ALL"},
	"AMD": {Symbol: "\u0534", DecimalDigits: 2, Code: "AMD"},
	"AOA": {Symbol: "Kz", DecimalDigits: 2, Code: "AOA"},
	"ARS": {Symbol: "$", DecimalDigits: 2, Code: "ARS"},
	"AUD": {Symbol: "$", DecimalDigits: 2, Code: "AUD"},
	"AWG": {Symbol: "\u0192", DecimalDigits: 2, Code: "AWG"},
	"AZN": {Symbol: "\u043c\u0430\u043d", DecimalDigits: 2, Code: "AZN"},
	"BAM": {Symbol: "\u041a\u041c", DecimalDigits: 2, Code: "BAM"},
	"BBD": {Symbol: "$", DecimalDigits: 2, Code: "BBD"},
	"BDT": {Symbol: "\u09f3", DecimalDigits: 2, Code: "BDT"},
	"BGN": {Symbol: "\u043b\u0432", DecimalDigits: 2, Code: "BGN"},
	"BHD": {Symbol: "\u0628.\u062f", DecimalDigits: 3, Code: "BHD"},
	"BIF": {Symbol: "\u20a3", DecimalDigits: 0, Code: "BIF"},
	"BMD": {Symbol: "$", DecimalDigits: 2, Code: "BMD"},
	"BND": {Symbol: "$", DecimalDigits: 2, Code: "BND"},
	"BOB": {Symbol: "Bs.", DecimalDigits: 2, Code: "BOB"},
	"BRL": {Symbol: "R$", DecimalDigits: 2, Code: "BRL"},
	"BSD": {Symbol: "$", DecimalDigits: 2, Code: "BSD"},
	"BTN": {Symbol: "", DecimalDigits: 2, Code: "BTN"},
	"BWP": {Symbol: "P", DecimalDigits: 2, Code: "BWP"},
	"BYN": {Symbol: "Br", DecimalDigits: 2, Code: "BYN"},
	"BZD": {Symbol: "$", DecimalDigits: 2, Code: "BZD"},
	"CAD": {Symbol: "$", DecimalDigits: 2, Code: "CAD"},
	"CDF": {Symbol: "\u20a3", DecimalDigits: 2, Code: "CDF"},
	"CHF": {Symbol: "\u20a3", DecimalDigits: 2, Code: "CHF"},
	"CLP": {Symbol: "$", DecimalDigits: 0, Code: "CLP"},
	"CNY": {Symbol: "\u00a5", DecimalDigits: 2, Code: "CNY"},
	"COP": {Symbol: "$", DecimalDigits: 2, Code: "COP"},
	"CRC": {Symbol: "\u20a1", DecimalDigits: 2, Code: "CRC"},
	"CUP": {Symbol: "$", DecimalDigits: 2, Code: "CUP"},
	"CVE": {Symbol: "$", DecimalDigits: 2, Code: "CVE"},
	"CZK": {Symbol: "K\u010d", DecimalDigits: 2, Code: "CZK"},
	"DJF": {Symbol: "\u20a3", DecimalDigits: 0, Code: "DJF"},
	"DKK": {Symbol: "kr", DecimalDigits: 2, Code: "DKK"},
	"DOP": {Symbol: "$", DecimalDigits: 2, Code: "DOP"},
	"DZD": {Symbol: "\u062f.\u062c", DecimalDigits: 2, Code: "DZD"},
	"EGP": {Symbol: "\u00a3", DecimalDigits: 2, Code: "EGP"},
	"ERN": {Symbol: "Nfk", DecimalDigits: 2, Code: "ERN"},
	"ETB": {Symbol: "", DecimalDigits: 2, Code: "ETB"},
	"EUR": {Symbol: "\u20ac", DecimalDigits: 2, Code: "EUR"},
	"FJD": {Symbol: "$", DecimalDigits: 2, Code: "FJD"},
	"FKP": {Symbol: "\u00a3", DecimalDigits: 2, Code: "FKP"},
	"GBP": {Symbol: "\u00a3", DecimalDigits: 2, Code: "GBP"},
	"GEL": {Symbol: "\u10da", DecimalDigits: 2, Code: "GEL"},
	"GHS": {Symbol: "\u20b5", DecimalDigits: 2, Code: "GHS"},
	"GIP": {Symbol: "\u00a3", DecimalDigits: 2, Code: "GIP"},
	"GMD": {Symbol: "D", DecimalDigits: 2, Code: "GMD"},
	"GNF": {Symbol: "\u20a3", DecimalDigits: 0, Code: "GNF"},
	"GTQ": {Symbol: "Q", DecimalDigits: 2, Code: "GTQ"},
	"GYD": {Symbol: "$", DecimalDigits: 2, Code: "GYD"},
	"HKD": {Symbol: "$", DecimalDigits: 2, Code: "HKD"},
	"HNL": {Symbol: "L", DecimalDigits: 2, Code: "HNL"},
	"HRK": {Symbol: "Kn", DecimalDigits: 2, Code: "HRK"},
	"HTG": {Symbol: "G", DecimalDigits: 2, Code: "HTG"},
	"HUF": {Symbol: "Ft", DecimalDigits: 2, Code: "HUF"},
	"IDR": {Symbol: "Rp", DecimalDigits: 2, Code: "IDR"},
	"ILS": {Symbol: "\u20aa", DecimalDigits: 2, Code: "ILS"},
	"INR": {Symbol: "\u20b9", DecimalDigits: 2, Code: "INR"},
	"IQD": {Symbol: "\u0639.\u062f", DecimalDigits: 3, Code: "IQD"},
	"IRR": {Symbol: "\ufdfc", DecimalDigits: 2, Code: "IRR"},
	"ISK": {Symbol: "Kr", DecimalDigits: 0, Code: "ISK"},
	"JMD": {Symbol: "$", DecimalDigits: 2, Code: "JMD"},
	"JOD": {Symbol: "\u062f.\u0627", DecimalDigits: 3, Code: "JOD"},
	"JPY": {Symbol: "\u00a5", DecimalDigits: 0, Code: "JPY"},
	"KES": {Symbol: "Sh", DecimalDigits: 2, Code: "KES"},
	"KGS": {Symbol: "", DecimalDigits: 2, Code: "KGS"},
	"KHR": {Symbol: "\u17db", DecimalDigits: 2, Code: "KHR"},
	"KPW": {Symbol: "\u20a9", DecimalDigits: 2, Code: "KPW"},
	"KRW": {Symbol: "\u20a9", DecimalDigits: 0, Code: "KRW"},
	"KWD": {Symbol: "\u062f.\u0643", DecimalDigits: 3, Code: "KWD"},
	"KYD": {Symbol: "$", DecimalDigits: 2, Code: "KYD"},
	"KZT": {Symbol: "\u3012", DecimalDigits: 2, Code: "KZT"},
	"LAK": {Symbol: "\u20ad", DecimalDigits: 2, Code: "LAK"},
	"LBP": {Symbol: "\u0644.\u0644", DecimalDigits: 2, Code: "LBP"},
	"LKR": {Symbol: "Rs", DecimalDigits: 2, Code: "LKR"},
	"LRD": {Symbol: "$", DecimalDigits: 2, Code: "LRD"},
	"LSL": {Symbol: "L", DecimalDigits: 2, Code: "LSL"},
	"LYD": {Symbol: "\u0644.\u062f", DecimalDigits: 3, Code: "LYD"},
	"MAD": {Symbol: "\u062f.\u0645.", DecimalDigits: 2, Code: "MAD"},
	"MDL": {Symbol: "L", DecimalDigits: 2, Code: "MDL"},
	"MKD": {Symbol: "\u0434\u0435\u043d", DecimalDigits: 2, Code: "MKD"},
	"MMK": {Symbol: "K", DecimalDigits: 2, Code: "MMK"},
	"MNT": {Symbol: "\u20ae", DecimalDigits: 2, Code: "MNT"},
	"MOP": {Symbol: "P", DecimalDigits: 2, Code: "MOP"},
	"MUR": {Symbol: "\u20a8", DecimalDigits: 2, Code: "MUR"},
	"MVR": {Symbol: "\u0783.", DecimalDigits: 2, Code: "MVR"},
	"MWK": {Symbol: "MK", DecimalDigits: 2, Code: "MWK"},
	"MXN": {Symbol: "$", DecimalDigits: 2, Code: "MXN"},
	"MYR": {Symbol: "RM", DecimalDigits: 2, Code: "MYR"},
	"MZN": {Symbol: "MTn", DecimalDigits: 2, Code: "MZN"},
	"NAD": {Symbol: "$", DecimalDigits: 2, Code: "NAD"},
	"NGN": {Symbol: "\u20a6", DecimalDigits: 2, Code: "NGN"},
	"NIO": {Symbol: "C$", DecimalDigits: 2, Code: "NIO"},
	"NOK": {Symbol: "kr", DecimalDigits: 2, Code: "NOK"},
	"NPR": {Symbol: "\u20a8", DecimalDigits: 2, Code: "NPR"},
	"NZD": {Symbol: "$", DecimalDigits: 2, Code: "NZD"},
	"OMR": {Symbol: "\u0631.\u0639.", DecimalDigits: 3, Code: "OMR"},
	"PAB": {Symbol: "B/.", DecimalDigits: 2, Code: "PAB"},
	"PEN": {Symbol: "S/.", DecimalDigits: 2, Code: "PEN"},
	"PGK": {Symbol: "K", DecimalDigits: 2, Code: "PGK"},
	"PHP": {Symbol: "\u20b1", DecimalDigits: 2, Code: "PHP"},
	"PKR": {Symbol: "\u20a8", DecimalDigits: 2, Code: "PKR"},
	"PLN": {Symbol: "z\u0142", DecimalDigits: 2, Code: "PLN"},
	"PYG": {Symbol: "\u20b2", DecimalDigits: 0, Code: "PYG"},
	"QAR": {Symbol: "\u0631.\u0642", DecimalDigits: 2, Code: "QAR"},
	"RON": {Symbol: "L", DecimalDigits: 2, Code: "RON"},
	"RSD": {Symbol: "din", DecimalDigits: 2, Code: "RSD"},
	"RUB": {Symbol: "\u0440.", DecimalDigits: 2, Code: "RUB"},
	"RWF": {Symbol: "\u20a3", DecimalDigits: 0, Code: "RWF"},
	"SAR": {Symbol: "\u0631.\u0633", DecimalDigits: 2, Code: "SAR"},
	"SBD": {Symbol: "$", DecimalDigits: 2, Code: "SBD"},
	"SCR": {Symbol: "\u20a8", DecimalDigits: 2, Code: "SCR"},
	"SDG": {Symbol: "\u00a3", DecimalDigits: 2, Code: "SDG"},
	"SEK": {Symbol: "kr", DecimalDigits: 2, Code: "SEK"},
	"SGD": {Symbol: "$", DecimalDigits: 2, Code: "SGD"},
	"SHP": {Symbol: "\u00a3", DecimalDigits: 2, Code: "SHP"},
	"SLL": {Symbol: "Le", DecimalDigits: 2, Code: "SLL"},
	"SOS": {Symbol: "Sh", DecimalDigits: 2, Code: "SOS"},
	"SRD": {Symbol: "$", DecimalDigits: 2, Code: "SRD"},
	"SYP": {Symbol: "\u0644.\u0633", DecimalDigits: 2, Code: "SYP"},
	"SZL": {Symbol: "L", DecimalDigits: 2, Code: "SZL"},
	"THB": {Symbol: "\u0e3f", DecimalDigits: 2, Code: "THB"},
	"TJS": {Symbol: "\u0405\u041c", DecimalDigits: 2, Code: "TJS"},
	"TMT": {Symbol: "m", DecimalDigits: 2, Code: "TMT"},
	"TND": {Symbol: "\u062f.\u062a", DecimalDigits: 3, Code: "TND"},
	"TOP": {Symbol: "T$", DecimalDigits: 2, Code: "TOP"},
	"TRY": {Symbol: "\u20a4", DecimalDigits: 2, Code: "TRY"},
	"TTD": {Symbol: "$", DecimalDigits: 2, Code: "TTD"},
	"TWD": {Symbol: "$", DecimalDigits: 2, Code: "TWD"},
	"TZS": {Symbol: "Sh", DecimalDigits: 2, Code: "TZS"},
	"UAH": {Symbol: "\u20b4", DecimalDigits: 2, Code: "UAH"},
	"UGX": {Symbol: "Sh", DecimalDigits: 0, Code: "UGX"},
	"USD": {Symbol: "$", DecimalDigits: 2, Code: "USD"},
	"UYU": {Symbol: "$", DecimalDigits: 2, Code: "UYU"},
	"UZS": {Symbol: "", DecimalDigits: 2, Code: "UZS"},
	"VND": {Symbol: "\u20ab", DecimalDigits: 0, Code: "VND"},
	"VUV": {Symbol: "Vt", DecimalDigits: 0, Code: "VUV"},
	"WST": {Symbol: "T", DecimalDigits: 2, Code: "WST"},
	"XAF": {Symbol: "\u20a3", DecimalDigits: 0, Code: "XAF"},
	"XCD": {Symbol: "$", DecimalDigits: 2, Code: "XCD"},
	"XPF": {Symbol: "\u20a3", DecimalDigits: 0, Code: "XPF"},
	"YER": {Symbol: "\ufdfc", DecimalDigits: 2, Code: "YER"},
	"ZAR": {Symbol: "R", DecimalDigits: 2, Code: "ZAR"},
	"ZMW": {Symbol: "ZK", DecimalDigits: 2, Code: "ZMW"},
	"ZWL": {Symbol: "$", DecimalDigits: 2, Code: "ZWL"},
}
